### ISSUE TITLE
Support for Explanations for Correct and Incorrect Answers?

### ISSUE THREAD

**Issue by wlg13** [robbert-harms/ybe#1]
As I read the documentation, there is no support for explanations for correct and incorrect quiz answers. Explanations can help students learn, so it would be a plus if explanations were supported. Thanks!

**Comment by robbert-harms** [comment]
hi wlg13,

Thanks for your comments. Explanations are indeed currently not supported. I could add them though. My proposal would be something like this:

```yaml

- multiple_response:
    id: 2015_q1
    points: 1
    text: A simple multiple response question.
    answers:
        - answer:
            text: First answer
            correct: true
            hint: A hint for when the student chooses this answer
        - answer:
            text: Second answer
            hint: Another hint
        - answer:
            text: Third answer
            correct: true
    feedback:
        general: General feedback for after this question.
        on_correct: Feedback when the question was answered correctly.
        on_incorrect: Feedback shown when the question was answered incorrectly.
```

That is, every question will have a new section `feedback`. Feedback is meant to be shown after the question was answered. It will have at least the option `general` (for example, for open questions), while multiple choice and multiple response have the additional options `on_correct` and `on_incorrect`.

In addition, every multiple choice and multiple response question will have the item `hint`, which can for example be shown when that answer is selected. What to do with them exactly is up to the application using the Ybe database.

Would that cover your use cases?

Best,

Robbert

**Comment by wlg13** [comment]
Yes, this would be it. For a bit more information, my use case involved Canvas LMS Quizzes. I've got a number of quizzes in Canvas and I'd like to mix and match questions across them; it is a real chore in Canvas currently to do this. Thus, I could imagine many users for this code. I have enclosed a qti file generated in Canvas that includes the different types of feedback. Thank you.
[econ-104-sec-1-sp21-quiz-export (1).zip](https://github.com/robbert-harms/ybe/files/5877669/econ-104-sec-1-sp21-quiz-export.1.zip)

**Comment by robbert-harms** [comment]
Hi wlg13,

Yes, I think I understand. You want to do: QTI -> Ybe -> QTI and use Ybe for shuffling questions.  This is exactly where Ybe was made for. What is indeed currently missing is including hints and explanations. I did not need it for my work, but I will add it nonetheless. Let me get back to you in a few days, I will need to find some free time to implement it.

Best,

Robbert

**Comment by wlg13** [comment]
Yes, this is indeed the use case. Let me add that I'll promote it here at Penn State among my colleagues who use Canvas Quizzes and among learning designers (we have more than 100) who design online courses. Thank you.

**Comment by robbert-harms** [comment]
hi Bill,

I did some work towards implementing this feature request. Ybe now supports loading QTI with hints and explanations. For example, loading your QTI with the latest development branch results in:

```yaml
ybe_version: 0.2.3

info:
    title: ybe <--> Canvas Quiz Illustration
    date: 2021-01-28

questions:
- multiple_choice:
    id: g553e22aa1d8288d45ef090b0e8351ed0
    points: 1.0
    text: !html <div><p>Question 1.</p></div>
    feedback:
        general: !html <p><span>Here's the explanation for the correct and incorrect answer (or "general comments").</span></p>
        on_correct: !html <p>Here's the explanation for the correct answer.</p>
        on_incorrect: !html <p><span>Here's the explanation for the incorrect answer.</span></p>
    answers:
        - answer:
            text: A
            correct: true
            hint: !html <p>A is the answer because it is first.</p>
        - answer:
            text: B
            hint: !html <p>A is not the answer because it is second.</p>
        - answer:
            text: ''
        - answer:
            text: ''
```

It seems to cover the comments you mentioned. For the next iteration I'll add writing QTI's as well.

If you want to test this new feature, you will have to install manually using Github. When QTI writing is done I will push a new version.

If it is useful please do promote it. Maybe one day it can be added to Canvas as an additional import/export functionality.

Best, 

Robbert

**Comment by robbert-harms** [comment]
Hi Bill,

I added QTI writing support for the comments and hints. The updates are now in Ybe version 0.3.0. A full roundtrip conversion of your QTI file can be done with, for example, this code:

```python
from ybe import read_qti_zip, write_ybe_file, read_ybe_file, write_qti_zip
from ybe.lib.qti_writer import ConvertCanvasEquations

ybe_exam = read_qti_zip('example_with_comments.zip')
write_ybe_file(ybe_exam, 'example_with_comments.ybe', minimal=True)

ybe_from_ybe = read_ybe_file('example_with_comments.ybe')
write_qti_zip(ybe_from_ybe, 'example_with_comments_ybed.zip', text_formatter=ConvertCanvasEquations())
```

Let me know if this works for you. 

Looking forward to the news,

Robbert

**Comment by wlg13** [comment]
Robbert -

Happy to test. I tried first converting the attached (an actual file that I'll be working with) to yaml and there seems to be one issue. Question 6 (starts with "Which ones of the") has multiple answers and it didn't seem to convert correctly to the yaml format (see attached). To continue testing, in this yaml file one answer was selected as correct and then converted back to qti, but didn't get a thing when I loaded into Canvas. When I looked at the qti files, I didn't see any questions. Maybe worth a look? 
Thanks, 
   Bill
![question_in_yaml](https://user-images.githubusercontent.com/47542061/106348350-a1d90100-6293-11eb-9e30-3b048152ea68.png)
 
[econ-104-sec-1-fa20-quiz-export (5).zip](https://github.com/robbert-harms/ybe/files/5897437/econ-104-sec-1-fa20-quiz-export.5.zip)

**Comment by robbert-harms** [comment]
Hi Bill,

Thank you for your comments. There was indeed a problem parsing the correct answers of multiple response questions, in the case of comments to the questions. I fixed it and released version 0.3.1.

For me it now parses correctly. For the question you indicated the parsed yaml now reads:

```yaml
- multiple_response:
    id: ged19adfed59a65c6748955c50f09f9ac
    points: 2.0
    text: !html <div><p>Which ones of the following have ...</p></div>
    answers:
        - answer:
            text: real GDP
            correct: true
            hint: !html <p>The percent ...</p>
        - answer:
            text: real price
            hint: !html <p>There is no...</p>
        - answer:
            text: CPI
            correct: true
            hint: !html <p>The percentage ...</p>
        - answer:
            text: the GDP deflator
            correct: true
            hint: !html <p>The percentage...</p>
    feedback:
        general: !html <p>The percentage ...</p>
        on_correct: !html <p>The percentage change ...</p>
        on_incorrect: !html <p>The percentage change ...</p>
```

One thing I noticed, is that your YAML output reads ``text_html``. This is syntax from a previous version (0.2.*). In the newer versions I changed this to read ``text: !html ...``. To me this indicates that you are running with an older version. Could you update Ybe and try again? If you are using PIP, updating can be done with: 
``pip install --upgrade ybe``

Let me know how you fare,

Robbert
